[package]
name = "storybuilder-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.23.0", features = ["full"] }
tokio-tungstenite = "*"
dotenv = "0.15.0"
url = "2.3.1"
